// Generated from botany-catalog.json. Do not edit by hand.
internal static partial class BotanicaCatalog {
    private static void PopulateGeneratedCatalog() {
        Add(new Entry("Quassia_Amara_flowers", "Flor de quássia-amarga", "Bitter quassia flower", "Flor de cuasia amarga", "Quassia amara", "quassia_amara", "alta", "", ""));
        Add(new Entry("Quassia_Amara_flowers_Dryed", "Flor de quássia-amarga (seca)", "Bitter quassia flower (dried)", "Flor de cuasia amarga (seca)", "Quassia amara", "quassia_amara", "alta", "", ""));
        Add(new Entry("QuassiaAmara_Seeds", "Semente de quássia-amarga", "Bitter quassia seed", "Semilla de cuasia amarga", "Quassia amara", "quassia_amara", "alta", "", ""));
        Add(new Entry("Cocona_fruit", "Maná-cubiu / tomate-de-índio", "Cocona / Indian tomato", "Cocona / tomate de indio", "Solanum sessiliflorum", "cocona", "media_alta", "", ""));
        Add(new Entry("Cocona_fruit_Spoiled", "Maná-cubiu / tomate-de-índio (estragado)", "Cocona / Indian tomato (spoiled)", "Cocona / tomate de indio (estropeado)", "Solanum sessiliflorum", "cocona", "media_alta", "", ""));
        Add(new Entry("Cocona_Seeds", "Sementes de maná-cubiu", "Cocona seeds", "Semillas de cocona", "Solanum sessiliflorum", "cocona", "media_alta", "", ""));
        Add(new Entry("monstera_deliciosa_flower", "Flor de costela-de-adão", "Swiss cheese plant flower", "Flor de costilla de Adán", "Monstera deliciosa", "monstera_deliciosa", "alta", "", ""));
        Add(new Entry("monstera_deliciosa_flower_Dryed", "Flor de costela-de-adão (seca)", "Swiss cheese plant flower (dried)", "Flor de costilla de Adán (seca)", "Monstera deliciosa", "monstera_deliciosa", "alta", "", ""));
        Add(new Entry("monstera_deliciosa_fruit", "Banana-ananás (fruto da costela-de-adão)", "Ceriman (Swiss cheese plant fruit)", "Piñanona (fruto de costilla de Adán)", "Monstera deliciosa", "monstera_deliciosa", "alta", "", ""));
        Add(new Entry("Monstera_Seeds", "Sementes de costela-de-adão", "Swiss cheese plant seeds", "Semillas de costilla de Adán", "Monstera deliciosa", "monstera_deliciosa", "alta", "", ""));
        Add(new Entry("Plantain_lily_leaf", "Folha de hosta / funkia", "Plantain lily leaf", "Hoja de hosta", "Hosta spp.", "plantain_lily", "alta_para_genero", "", ""));
        Add(new Entry("plantain_lilly_flowers", "Flor de hosta / funkia", "Plantain lily flower", "Flor de hosta", "Hosta spp.", "plantain_lily", "alta_para_genero", "", ""));
        Add(new Entry("plantain_lilly_flowers_Dryed", "Flor de hosta / funkia (seca)", "Plantain lily flower (dried)", "Flor de hosta (seca)", "Hosta spp.", "plantain_lily", "alta_para_genero", "", ""));
        Add(new Entry("PlantainLilly_Seeds", "Propágulo de hosta / funkia", "Plantain lily propagule", "Propágulo de hosta", "Hosta spp.", "plantain_lily", "alta_para_genero", "", ""));
        Add(new Entry("Guanabana_Fruit", "Graviola / guanábana", "Soursop", "Guanábana", "Annona muricata", "guanabana", "alta", "", ""));
        Add(new Entry("Guanabana_Fruit_Spoiled", "Graviola / guanábana (estragada)", "Soursop (spoiled)", "Guanábana (estropeada)", "Annona muricata", "guanabana", "alta", "", ""));
        Add(new Entry("Guanabana_Seeds", "Sementes de graviola", "Soursop seeds", "Semillas de guanábana", "Annona muricata", "guanabana", "alta", "", ""));
        Add(new Entry("Malanga_bulb", "Cormo de malanga", "Malanga corm", "Cormo de malanga", "Xanthosoma spp.", "malanga", "alta_para_genero", "", ""));
        Add(new Entry("Malanga_bulb_cooked", "Cormo de malanga (cozido)", "Malanga corm (cooked)", "Cormo de malanga (cocido)", "Xanthosoma spp.", "malanga", "alta_para_genero", "", ""));
        Add(new Entry("Malanga_bulb_Spoiled", "Cormo de malanga (estragado)", "Malanga corm (spoiled)", "Cormo de malanga (estropeado)", "Xanthosoma spp.", "malanga", "alta_para_genero", "", ""));
        Add(new Entry("Malanga_Bulb_dryed", "Cormo de malanga (seco)", "Malanga corm (dried)", "Cormo de malanga (seco)", "Xanthosoma spp.", "malanga", "alta_para_genero", "", ""));
        Add(new Entry("Malanga_Seeds", "Raiz de malanga para plantio", "Malanga root for planting", "Raíz de malanga para plantar", "Xanthosoma spp.", "malanga", "alta_para_genero", "", ""));
        Add(new Entry("Cassava_bulb", "Raiz de mandioca", "Cassava root", "Raíz de yuca", "Manihot esculenta", "cassava", "alta", "", ""));
        Add(new Entry("Cassava_bulb_Cooked", "Raiz de mandioca (cozida)", "Cassava root (cooked)", "Raíz de yuca (cocida)", "Manihot esculenta", "cassava", "alta", "", ""));
        Add(new Entry("Cassava_bulb_Spoiled", "Raiz de mandioca (estragada)", "Cassava root (spoiled)", "Raíz de yuca (estropeada)", "Manihot esculenta", "cassava", "alta", "", ""));
        Add(new Entry("Cassava_bulb_dryed", "Raiz de mandioca (seca)", "Cassava root (dried)", "Raíz de yuca (seca)", "Manihot esculenta", "cassava", "alta", "", ""));
        Add(new Entry("Casava_Seeds", "Raiz de mandioca para plantio", "Cassava root for planting", "Raíz de yuca para plantar", "Manihot esculenta", "cassava", "alta", "", ""));
        Add(new Entry("Albahaca_Leaf", "Folha de manjericão-de-folha-larga", "Broadleaf basil leaf", "Hoja de albahaca de hoja ancha", "Ocimum basilicum", "albahaca", "media", "", ""));
        Add(new Entry("Albahaca_Flower", "Flor de manjericão-de-folha-larga", "Broadleaf basil flower", "Flor de albahaca de hoja ancha", "Ocimum basilicum", "albahaca", "media", "", ""));
        Add(new Entry("Albahaca_flower_Dryed", "Flor de manjericão-de-folha-larga (seca)", "Broadleaf basil flower (dried)", "Flor de albahaca de hoja ancha (seca)", "Ocimum basilicum", "albahaca", "media", "", ""));
        Add(new Entry("Albahaca_Seeds", "Sementes de manjericão-de-folha-larga", "Broadleaf basil seeds", "Semillas de albahaca de hoja ancha", "Ocimum basilicum", "albahaca", "media", "", ""));
        Add(new Entry("Molineria_leaf", "Folha de molineria", "Molineria leaf", "Hoja de molineria", "Molineria capitulata", "molineria", "media", "Curculigo capitulata", ""));
        Add(new Entry("molineria_flowers", "Flor de molineria", "Molineria flower", "Flor de molineria", "Molineria capitulata", "molineria", "media", "Curculigo capitulata", ""));
        Add(new Entry("molineria_flowers_Dryed", "Flor de molineria (seca)", "Molineria flower (dried)", "Flor de molineria (seca)", "Molineria capitulata", "molineria", "media", "Curculigo capitulata", ""));
        Add(new Entry("Molineria_Seeds", "Propágulo de molineria", "Molineria propagule", "Propágulo de molineria", "Molineria capitulata", "molineria", "media", "Curculigo capitulata", ""));
        Add(new Entry("Tobacco_Leaf", "Folha de tabaco", "Tobacco leaf", "Hoja de tabaco", "Nicotiana tabacum", "tobacco", "alta", "", ""));
        Add(new Entry("Dryed_Tobacco_Leaf", "Folha de tabaco (seca)", "Tobacco leaf (dried)", "Hoja de tabaco (seca)", "Nicotiana tabacum", "tobacco", "alta", "", ""));
        Add(new Entry("tobacco_flowers", "Flor de tabaco", "Tobacco flower", "Flor de tabaco", "Nicotiana tabacum", "tobacco", "alta", "", ""));
        Add(new Entry("tobacco_flowers_Dryed", "Flor de tabaco (seca)", "Tobacco flower (dried)", "Flor de tabaco (seca)", "Nicotiana tabacum", "tobacco", "alta", "", ""));
        Add(new Entry("Tobacco_Seeds", "Sementes de tabaco", "Tobacco seeds", "Semillas de tabaco", "Nicotiana tabacum", "tobacco", "alta", "", ""));
        Add(new Entry("psychotria_viridis", "Folhas de chacrona", "Chacruna leaves", "Hojas de chacruna", "Psychotria viridis", "psychotria", "alta", "", ""));
        Add(new Entry("psychotria_viridis_Dryed", "Folhas de chacrona (secas)", "Chacruna leaves (dried)", "Hojas de chacruna (secas)", "Psychotria viridis", "psychotria", "alta", "", ""));
        Add(new Entry("psychotria_viridis_berries", "Bagas de psychotria", "Chacruna berries", "Bayas de chacruna", "Psychotria viridis", "psychotria", "alta", "", ""));
        Add(new Entry("psychotria_viridis_berries_Dryed", "Bagas de psychotria (secas)", "Chacruna berries (dried)", "Bayas de chacruna (secas)", "Psychotria viridis", "psychotria", "alta", "", ""));
        Add(new Entry("Psychotria_Seeds", "Sementes de psychotria", "Chacruna seeds", "Semillas de chacruna", "Psychotria viridis", "psychotria", "alta", "", ""));
        Add(new Entry("banisteriopsis_scraps", "Fragmentos de mariri / cipó-caapi", "Caapi vine scraps", "Fragmentos de liana caapi", "Banisteriopsis caapi", "banisteriopsis", "alta", "", ""));
        Add(new Entry("coca_leafs", "Folhas de coca", "Coca leaves", "Hojas de coca", "Erythroxylum coca", "coca", "alta", "", ""));
        Add(new Entry("Brazil_nut_whole", "Ouriço de castanha-do-pará", "Brazil nut pod", "Cápsula de nuez de Brasil", "Bertholletia excelsa", "brazil_nut", "alta", "", ""));
        Add(new Entry("Brazil_nut", "Castanha-do-pará", "Brazil nut", "Nuez de Brasil", "Bertholletia excelsa", "brazil_nut", "alta", "", ""));
        Add(new Entry("Brazil_nut_Spoiled", "Castanha-do-pará (estragada)", "Brazil nut (spoiled)", "Nuez de Brasil (estropeada)", "Bertholletia excelsa", "brazil_nut", "alta", "", ""));
        Add(new Entry("Brazilian_Seeds", "Castanha-do-pará para plantio", "Brazil nut for planting", "Nuez de Brasil para plantar", "Bertholletia excelsa", "brazil_nut", "alta", "", ""));
        Add(new Entry("Raffia_nut", "Fruto de palmeira-ráfia", "Raffia palm fruit", "Fruto de palmera rafia", "Raphia spp.", "raffia", "alta_para_genero", "", ""));
        Add(new Entry("Raffia_nut_Spoiled", "Fruto de palmeira-ráfia (estragado)", "Raffia palm fruit (spoiled)", "Fruto de palmera rafia (estropeado)", "Raphia spp.", "raffia", "alta_para_genero", "", ""));
        Add(new Entry("Raffia_Seeds", "Semente de palmeira-ráfia", "Raffia palm seed", "Semilla de palmera rafia", "Raphia spp.", "raffia", "alta_para_genero", "", ""));
        Add(new Entry("Banana", "Banana", "Banana", "Banana", "Musa spp.", "banana", "alta_para_genero", "", ""));
        Add(new Entry("Banana_Spoiled", "Banana (estragada)", "Banana (spoiled)", "Banana (estropeada)", "Musa spp.", "banana", "alta_para_genero", "", ""));
        Add(new Entry("Banana_Seeds", "Sementes de banana", "Banana seeds", "Semillas de banana", "Musa spp.", "banana", "alta_para_genero", "", ""));
        Add(new Entry("Banana_Leaf", "Folha de bananeira", "Banana leaf", "Hoja de bananera", "Musa spp.", "banana", "alta_para_genero", "", ""));
        Add(new Entry("Coconut_Green", "Coco-verde", "Green coconut", "Coco verde", "Cocos nucifera", "coconut", "alta", "", ""));
        Add(new Entry("Coconut", "Coco", "Coconut", "Coco", "Cocos nucifera", "coconut", "alta", "", ""));
        Add(new Entry("Coconut_flesh", "Polpa de coco", "Coconut flesh", "Pulpa de coco", "Cocos nucifera", "coconut", "alta", "", ""));
        Add(new Entry("Coconut_flesh_Cooked", "Polpa de coco (cozida)", "Coconut flesh (cooked)", "Pulpa de coco (cocida)", "Cocos nucifera", "coconut", "alta", "", ""));
        Add(new Entry("Coconut_flesh_Spoiled", "Polpa de coco (estragada)", "Coconut flesh (spoiled)", "Pulpa de coco (estropeada)", "Cocos nucifera", "coconut", "alta", "", ""));
        Add(new Entry("Coconut_Shell_Flesh", "Meio coco com polpa", "Coconut half with flesh", "Medio coco con pulpa", "Cocos nucifera", "coconut", "alta", "", ""));
        Add(new Entry("Coconut_Shell_Flesh_Spoiled", "Meio coco com polpa (estragada)", "Coconut half with flesh (spoiled)", "Medio coco con pulpa (estropeada)", "Cocos nucifera", "coconut", "alta", "", ""));
        Add(new Entry("lily_flower", "Flor de nenúfar", "Water lily flower", "Flor de nenúfar", "Nymphaea spp.", "water_lily", "alta_para_genero", "", ""));
        Add(new Entry("Ficus_leaf", "Folha de figueira", "Fig leaf", "Hoja de higuera", "Ficus spp.", "ficus", "alta_para_genero", "", ""));
        Add(new Entry("Palm_heart", "Palmito", "Heart of palm", "Palmito", "Arecaceae sp.", "palm_heart", "baixa_para_especie", "", ""));
        Add(new Entry("Palm_heart_Spoiled", "Palmito (estragado)", "Heart of palm (spoiled)", "Palmito (estropeado)", "Arecaceae sp.", "palm_heart", "baixa_para_especie", "", ""));
        Add(new Entry("Palm_Heart_dryed", "Palmito (seco)", "Heart of palm (dried)", "Palmito (seco)", "Arecaceae sp.", "palm_heart", "baixa_para_especie", "", ""));
        Add(new Entry("Phallus_indusiatus", "Cogumelo véu-de-noiva", "Veiled lady mushroom", "Hongo velo de novia", "Phallus indusiatus", "phallus_indusiatus", "alta", "", ""));
        Add(new Entry("Phallus_indusiatus_Dryed", "Cogumelo véu-de-noiva (seco)", "Veiled lady mushroom (dried)", "Hongo velo de novia (seco)", "Phallus indusiatus", "phallus_indusiatus", "alta", "", ""));
        Add(new Entry("Phallus_indusiatus_Spoiled", "Cogumelo véu-de-noiva (estragado)", "Veiled lady mushroom (spoiled)", "Hongo velo de novia (estropeado)", "Phallus indusiatus", "phallus_indusiatus", "alta", "", ""));
        Add(new Entry("Gerronema_viridilucens", "Gerronema bioluminescente", "Bioluminescent gerronema", "Gerronema bioluminiscente", "Gerronema viridilucens", "gerronema_viridilucens", "alta", "", ""));
        Add(new Entry("Gerronema_viridilucens_dryed", "Gerronema bioluminescente (seco)", "Bioluminescent gerronema (dried)", "Gerronema bioluminiscente (seco)", "Gerronema viridilucens", "gerronema_viridilucens", "alta", "", ""));
        Add(new Entry("Gerronema_viridilucens_Spoiled", "Gerronema bioluminescente (estragado)", "Bioluminescent gerronema (spoiled)", "Gerronema bioluminiscente (estropeado)", "Gerronema viridilucens", "gerronema_viridilucens", "alta", "", ""));
        Add(new Entry("Gerronema_retiarium", "Gerronema retiário", "Reticulate gerronema", "Gerronema reticulado", "Gerronema retiarium", "gerronema_retiarium", "alta", "", ""));
        Add(new Entry("Gerronema_retiarium_dryed", "Gerronema retiário (seco)", "Reticulate gerronema (dried)", "Gerronema reticulado (seco)", "Gerronema retiarium", "gerronema_retiarium", "alta", "", ""));
        Add(new Entry("Gerronema_retiarium_Spoiled", "Gerronema retiário (estragado)", "Reticulate gerronema (spoiled)", "Gerronema reticulado (estropeado)", "Gerronema retiarium", "gerronema_retiarium", "alta", "", ""));
        Add(new Entry("indigo_blue_leptonia", "Leptônia-azul", "Indigo blue leptonia", "Leptonia azul índigo", "Entoloma subcarneum", "indigo_blue_leptonia", "media_alta", "", "Indigo Blue Leptonia"));
        Add(new Entry("indigo_blue_leptonia_dryed", "Leptônia-azul (seca)", "Indigo blue leptonia (dried)", "Leptonia azul índigo (seca)", "Entoloma subcarneum", "indigo_blue_leptonia", "media_alta", "", "Indigo Blue Leptonia"));
        Add(new Entry("indigo_blue_leptonia_Spoiled", "Leptônia-azul (estragada)", "Indigo blue leptonia (spoiled)", "Leptonia azul índigo (estropeada)", "Entoloma subcarneum", "indigo_blue_leptonia", "media_alta", "", "Indigo Blue Leptonia"));
        Add(new Entry("copa_hongo", "Cogumelo-de-copa / taça-escarlate", "Scarlet cup mushroom", "Hongo copa escarlata", "Sarcoscypha coccinea", "copa_hongo", "alta", "", ""));
        Add(new Entry("copa_hongo_dryed", "Cogumelo-de-copa / taça-escarlate (seco)", "Scarlet cup mushroom (dried)", "Hongo copa escarlata (seco)", "Sarcoscypha coccinea", "copa_hongo", "alta", "", ""));
        Add(new Entry("copa_hongo_Spoiled", "Cogumelo-de-copa / taça-escarlate (estragado)", "Scarlet cup mushroom (spoiled)", "Hongo copa escarlata (estropeado)", "Sarcoscypha coccinea", "copa_hongo", "alta", "", ""));
    }
}
